name: www.langkupar.com
favicon: null
layout_spectrum: 0.31391843291930854
typography_spectrum: 0.08250906132161617
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.6881102621555328
  lightness: 0.584633816499263
  saturation: 0.04894522996619344
  rhythmicContrast: 0.3511089168023318
purpose: []
